### ISSUE TITLE
Make the "row" key optional

### ISSUE THREAD

**Issue by quicksketch** [justafish/drupal_createapi#2]
When using feeds generated by this module, I couldn't figure out why the "row" keys were being added. In the generated feeds, it seems like it's just an unnecessary layer of nesting. Maybe this would be necessary on some sites (though I can't think of why), but for sites that don't want this key, perhaps it should be made optional?

``` php
function my_module_createapi_custom_entities_info() {
  $info = array();
  $info['articles'] = array(
    'version' => '1.0',
    'path' => 'articles',
    'wrapper' => 'articles',
    'row' => 'article', // <- Make this optional?
    ...
}
```

In this example, the "row" key is "nominee". Isn't it generally unneeded?

![createapi_keys](https://f.cloud.github.com/assets/100206/1303401/f5302a18-3154-11e3-8e37-a3ed3c10e621.png)

**Comment by justafish** [comment]
Committed, thanks!
